name: Build and (potentially) deploy to Cloudflare Pages


on: push


jobs:

  build-jekyll:
    runs-on: ubuntu-22.04
    container:
      image: ruby:3.3.1
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install gems
        run: bundle install
      - name: Build website
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-website
          if-no-files-found: error
          path: _site/

  deploy-to-cloudflare-pages:
    if: github.ref == 'refs/heads/main'
    needs: build-jekyll
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Download built website
        uses: actions/download-artifact@v4
        with:
          name: jekyll-website
          path: _site
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: jekyll-links
          directory: _site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
